<a href="https://colab.research.google.com/github/Zulu0739/newPytorch_ZTQ/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [3]:
my_list = [[1,2,3,4,5,6],[6,7,8,9]]
my_list

[[1, 2, 3, 4, 5, 6], [6, 7, 8, 9]]

In [11]:
np1 = np.random.rand(3,4)
np1

array([[0.34450529, 0.06454052, 0.05083482, 0.96678705],
       [0.51505212, 0.34272755, 0.09820561, 0.20425255],
       [0.56018998, 0.61670423, 0.03226915, 0.44647974]])

In [7]:
np1.dtype

dtype('float64')

In [13]:
tensor_2d = torch.randn(3,4)
tensor_2d.dtype

torch.float32

In [9]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [12]:
## Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.3445, 0.0645, 0.0508, 0.9668],
        [0.5151, 0.3427, 0.0982, 0.2043],
        [0.5602, 0.6167, 0.0323, 0.4465]], dtype=torch.float64)